name: Tests

on:
  pull_request:
    branches: main

jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
    - run: sleep 30 && echo "Failing test" && exit 1
  test-2:
    runs-on: ubuntu-latest
    steps:
    - run: sleep 30
